Create capture_url plugin
valibre-org/vln-api pull request #18
Opened 2021-02-12 05:30 UTC by JorgeVV

A plugin to generate screenshots from any website. See README.md

2021-02-12 15:20 UTC, olanod requested changes
Awesome! looks quite good, just the minor cosmetic changes.

2021-02-12 19:36 UTC, JorgeVV commented on plugins.json
> +  { "type": "native", "name": "capture_url", "prefix": "capture_url" }
Got it!

2021-02-22 06:27 UTC, olanod commented
Do you think we can do something about the webdriver server dependency with the failing tests?

2021-02-22 14:05 UTC, JorgeVV commented
Yes. I was thinking about what we last talked about: setting up Docker. I haven't got time and I'll be working on this issue in the next couple of day.

2021-03-17 11:44 UTC, JorgeVV commented
@olanod Finally 😄

2021-03-18 11:20 UTC, olanod reviewed
Changes look good :)  
Sorry if its late but I was thinking of a slight variation of the API that might be more ergonomic and then play better with the template rendering plugin.
Since returning a capture is actually fetching data, I think a `GET` request could work better here with the input data being just two query parameters, i.e. `?url=<URL>&d=<DIMENSIONS>`(dimensions can implement `FromStr` and then you just `.parse()` it), also comes with the added benefit of being easily cached by a CDN for example and we could shave off the _serde_ dependency.
I would add more details in the other PR but the idea is to leverage the conveniences of the HTTP protocol to generate the template with the other endpoint and automatically redirect here to get the capture all in one go, it could even work with a simple form without any extra code on the client side(no JS at all actually).

2021-04-13 06:50 UTC, olanod commented on plugins/capture_url/src/lib.rs
> +        (Cmd::Capture, Method::Get) => capture_handler(req).await,
Only change I can think is that this plugin maybe doesn't need the router dependency as it only does one thing, so just handlign get requests that come to its root should be good. That way the URL also becomes simpler as you would only do `curl http://api.valiu/capture-url?...`

2021-04-13 16:35 UTC, olanod approved these changes

2021-04-13 18:39 UTC, JorgeVV commented on plugins/capture_url/src/lib.rs
> +        (Cmd::Capture, Method::Get) => capture_handler(req).await,
Agreed and implemented 😄

2021-04-13 22:17 UTC, merged