feat:friendly tx-id
valibre-org/vln-api pull request #20
Opened 2021-02-15 18:12 UTC by stanly-johnson

Resolve #7

### Changes
- Util function to generate a user friendly tx-id. Encode first 32bits of given transaction-id using base58.
- added http-client to Cargo.toml to fix build error

2021-02-17 20:10 UTC, olanod requested changes
Hi! thanks for tackling this. What do you say about making this utility a bit more general purpose? It doesn't have to apply only to transaction ids(I'm not even sure yet about transactions having ids) but can be used as a way to "pretty print" binary data in general(making most sense for hashes). One option that comes to mind could be an extension trait for types that can be represented as bytes(e.g. `T: AsRef<[u8]>`), imagine a `Vec<u8>` or similar doing something like `data.short()` or `data.pretty()`. We could even get more strict and also require the  `core::hash::Hash` bound to ensure the data is random looking and we'll get a nice unique looking short ID but there might be cases we want to create the short ID for non hashes 🤔

2021-02-17 20:10 UTC, olanod commented on plugins/blockchain/src/util_txid.rs
> +        input.into()
I think we don't want the input to be any string(or no string at all?) preferably the function is fallible and returns a result, what happens when I pass `"foo"`(I think it panics), but more importantly what does it even mean to get the short id of `"foo"`?

2021-02-18 15:57 UTC, stanly-johnson commented on plugins/blockchain/src/util_txid.rs
> +        input.into()
Yes you're right. I'll convert this to a trait as you said above.

2021-02-22 06:32 UTC, olanod requested changes
Awesome! looks good. One last change, can you move this to the root maybe in a crate called `util`? this function won't actually be used in the blockchain plugin which is intended to be lower level and very general to work with any substrate chain, it will be used initially in the yet to be created `transfers` plugin or other higher level more Valiu specific plugins that the app will consume and sexy identifiers will be more handy.

2021-02-22 06:32 UTC, olanod commented on plugins/blockchain/Cargo.toml
> +http-client = "6.3.0"
I guess this one is not needed?

2021-02-22 11:53 UTC, stanly-johnson commented on plugins/blockchain/Cargo.toml
> +http-client = "6.3.0"
I'm not sure, removing this gives me a build error about `TlsStream` and `TcpStream`

2021-02-22 14:03 UTC, olanod approved these changes

2021-02-22 14:03 UTC, olanod commented on plugins/blockchain/Cargo.toml
> +http-client = "6.3.0"
Ok weird, I can look into that later

2021-02-22 14:03 UTC, olanod commented on plugins/blockchain/Cargo.toml
> +bs58 = "0.4.0"
But then what about this one? ✂️

2021-02-22 16:30 UTC, merged