Add html_renderer plugin
valibre-org/vln-api pull request #23
Opened 2021-03-17 12:01 UTC by JorgeVV

Plugin to store and render templates. The output can be piped to the plugin added in #18 to generate an image.

2021-04-13 18:42 UTC, JorgeVV commented
@olanod As discussed in #18, html renderer with redirection support.

2021-04-28 15:03 UTC, olanod requested changes

2021-04-29 13:09 UTC, olanod approved these changes
Awesome looks good! :)

2021-04-30 20:03 UTC, JorgeVV commented on plugins/html_renderer/src/lib.rs
> +                .map_err(|_| http::Error::from_str(StatusCode::BadRequest, ""))?;
Not really because trait is not implemented for `Result<String, ()>`, but given we are not discriminating between errors (must errors when registering are because of invalid handlebar template format) I changed it to an optional string that does implement the `Status` trait.

2021-05-01 09:54 UTC, olanod approved these changes

2021-05-01 21:32 UTC, merged